name: Pylint
on: [push, pull_request]
jobs:
  Pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1

      - name: install pylint and required pip packages
        run: |
          pip install pylint
          pip install beautifulsoup4
          pip install requests

      - name: run pylint
        shell: bash
        run: |
          pylint scrapers/*.py
